services:
  db:
    image: bitnamilegacy/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - mynet
  smtp:
    image: ghusta/fakesmtp
    ports:
      - "2525:25"
    networks:
      - mynet

  llm:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - mynet
    command: "serve"

  webserver:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - mynet
    environment:
      - DATASOURCE_JNDI
      - DATASOURCE_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - WILDFLY_ADMIN_PASSWORD
      - POSTGRES_DRIVER_VERSION
    depends_on:
      - db
      - smtp
      - llm

networks:
  mynet:
